In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [3]:
# Reading the CSV file
df = pd.read_csv(r"C:\Users\muthomig\Downloads\ibnr.csv")
df

AY    0      1      2      3      4
0  2014  100  150.0  180.0  200.0  225.0
1  2015  112  173.0  215.0  245.0    NaN
2  2016  118  185.0  233.0    NaN    NaN
3  2017  122  195.0    NaN    NaN    NaN
4  2018  125    NaN    NaN    NaN    NaN

In [5]:
df.set_index(df['AY'], inplace=True)
del df['AY']
df

0      1      2      3      4
AY                                   
2014  100  150.0  180.0  200.0  225.0
2015  112  173.0  215.0  245.0    NaN
2016  118  185.0  233.0    NaN    NaN
2017  122  195.0    NaN    NaN    NaN
2018  125    NaN    NaN    NaN    NaN

In [7]:
factors = []
for col in df.columns[:-1]:
    factors.append(df[str(int(col)+1)].sum() / df[col][:-int(col)-1].sum())
factors = np.array(factors)
factors

array([1.55530973, 1.23622047, 1.12658228, 1.125     ])

In [12]:
cum_factors = np.cumprod(factors[::-1])[::-1]
cum_factors

array([2.43684698, 1.56679209, 1.26740506, 1.125     ])

In [24]:
# Append the value 1
cum_factors = np.append(cum_factors, 1)

# Print the updated array
cum_factors

array([2.43684698, 1.56679209, 1.26740506, 1.125     , 1.        ])

In [38]:
# 
Incurred = []

# Loop through each row in the DataFrame
for i, row in df.iterrows():
    # Get the last non-NaN value from the row
    last_value = row.dropna().iloc[-1]  # Get the last valid entry
    Incurred.append(last_value)  # Add it to the result list

# Display the result
print(Incurred)

[225.0, 245.0, 233.0, 195.0, 125.0]


In [44]:
# Reverse the Incurred array so that the highest CDF matches with the lowest Incurred
Incurred_loss = Incurred[::-1]
Incurred_loss

[125.0, 195.0, 233.0, 245.0, 225.0]

In [52]:
# Calculate Ultimate values by multiplying CDFs with Incurred loss
Ultimate = cum_factors * Incurred_loss

# Create a DataFrame with the required columns
df = pd.DataFrame({
    'CDFs': cum_factors,
    'Incurred': Incurred_loss,
    'Ultimate': Ultimate
})
df

CDFs  Incurred    Ultimate
0  2.436847     125.0  304.605873
1  1.566792     195.0  305.524457
2  1.267405     233.0  295.305380
3  1.125000     245.0  275.625000
4  1.000000     225.0  225.000000

In [58]:
df['IBNR'] = df['Ultimate'].astype(float) - df['Incurred'].astype(float)
df

CDFs  Incurred    Ultimate        IBNR
0  2.436847     125.0  304.605873  179.605873
1  1.566792     195.0  305.524457  110.524457
2  1.267405     233.0  295.305380   62.305380
3  1.125000     245.0  275.625000   30.625000
4  1.000000     225.0  225.000000    0.000000

In [60]:
total_ibnr = df['IBNR'].sum()

# Display the total IBNR
print("Total IBNR:", total_ibnr)

Total IBNR: 383.0607094762064
